//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkHubBOL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;

    public partial class tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_User()
        {
            this.tbl_Url = new HashSet<tbl_Url>();
        }
    
        public int UserId { get; set; }
        [Required(ErrorMessage = "you should enter mail")]
        [EmailAddress]
        [UniqueEmail]
        public string UserEmail { get; set; }
        [Required(ErrorMessage ="you should enter password")]
        public string Password { get; set; }
        public string Role { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Url> tbl_Url { get; set; }
    }

    public class UniqueEmailAttribute : ValidationAttribute
    {
        protected override ValidationResult IsValid(object value, ValidationContext contex)
        {
            LinkHubDbEntities db = new LinkHubDbEntities();
            string emailValue = value.ToString();
            int count = db.tbl_User.Where(x => x.UserEmail == emailValue).Count();
            if (count != 0)
            {
                return new ValidationResult("Email is existed");
            }
            return ValidationResult.Success;
        }
    } // end class UniqueUrlAttribute
}
