//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkHubBOL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tbl_Url
    {
        public int UrlId { get; set; }
        [DisplayName("URL Title")]
        public string UrlTitle { get; set; }
        [DisplayName("URL")]
        public string Url { get; set; }
        [DisplayName("URL Description")]
        public string UrlDesc { get; set; }
        [DisplayName("Category")]
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string IsApproved { get; set; }
    
        public virtual tbl_Category tbl_Category { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
